name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWYzMDBjNGEtOGMwMS00MzgzLWE2YTctYmFmYjlkNDhiOGE1IiwidGVuYW50X2lkIjoiNzYyN2UyYWQ5MDIwODcwYWFmNGU4MjIxNmI0NTMyMmYwYjZmMjA4ZDk5MzMzZTI3OTA2NDhlODY4OThlZWQyMSIsImludGVybmFsX3NlY3JldCI6IjkxMTIzZGE0LTRjMjQtNDc0YS1hZDg1LWY4ODljNGIxMTZmMSJ9.XQaecvSYGHcAKw2huqnTUw-0Jw_bwJSCHTpp-f09HdI"